### ISSUE TITLE
Multitool: match-results-forward defines multiple ambiguous -p switches

### ISSUE THREAD

**Issue by dbjorge** [microsoft/sarif-sdk#1498]
In the `match-results-forward` command, multiple options define a `-p` switch:

```
> .\dotnet_tools\sarif.exe match-results-forward --help
SARIF Multitool 2.1.1
...
  -p, --previous                Path to a sarif log containing the previous set of results with result matching
                                annotations on a target (or empty if no previous log exists)
...
  -p, --pretty-print            (Default: false) Produce pretty-printed JSON output rather than compact form.
...
```

If you try to use the `-p` switch anyway, you get an unhelpful error like this:

```
    Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
       at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at CommandLine.Core.TypeLookup.FindTypeDescriptorAndSibling(String name, IEnumerable`1 specifications, StringComparer comparer)
       at CommandLine.Core.Switch.<>c__DisplayClass0_0.<Partition>b__0(Token t)
       at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
       at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
       at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
       at CommandLine.Core.TokenPartitioner.Partition(IEnumerable`1 tokens, Func`2 typeLookup)
       at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__5()
       at CommandLine.Core.InstanceChooser.MatchVerb(Func`3 tokenizer, IEnumerable`1 verbs, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors)
       at CommandLine.Core.InstanceChooser.<>c__DisplayClass0_0.<Choose>b__0()
       at CommandLine.Parser.ParseArguments(IEnumerable`1 args, Type[] types)
       at Microsoft.CodeAnalysis.Sarif.Multitool.Program.Main(String[] args)
```

The root cause is that the `-p` switch defined for the "previous" option in [ResultMatchingOptions.cs](https://github.com/microsoft/sarif-sdk/blob/master/src/Sarif.Multitool/ResultMatchingOptions.cs) and the `-p` switch defined for the "pretty-print" option in [CommonOptionsBase.cs](https://github.com/microsoft/sarif-sdk/blob/master/src/Sarif.Driver/Sdk/CommonOptionsBase.cs) conflict with one another.

**Comment by ScottLouvau** [comment]
Fixed in https://github.com/microsoft/sarif-sdk/pull/1520 and added a unit test to ensure this doesn't regress (for any of the modes).
