### ISSUE TITLE
Unit test fails when SDK is included as a submodule

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-sdk#2162]
Repro:

1. Include sarif-sdk as a submodule, for instance as we do in the SarifInternal repo: `SarifInternal\submodules\sarif-sdk`.

2. Changed directory to the submodule's directory `...\sarif-sdk`.

3. `git checkout master`

3. `BuildAndTest.cmd`

Expected: Tests should pass.

Actual: Two tests fail:
```
  Failed Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.InsertOptionalDataVisitor_PersistsAll [364 ms]
  Error Message:
   Expected object to be file:///C:/dev/SarifInternal/submodules/sarif-sdk/, but found file:///C:/dev/SarifInternal/.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.ConstructTestOutputFromInputResource(String inputResourceName, Object parameter) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 123
   at Microsoft.CodeAnalysis.Sarif.FileDiffingUnitTests.RunTest(String inputResourceName, String expectedOutputResourceName, Object parameter) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.Utilities.Sarif\FileDiffingUnitTests.cs:line 101
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.RunTest(String inputResourceName, OptionallyEmittedData optionallyEmittedData) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 159
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.InsertOptionalDataVisitor_PersistsAll() in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 235
[xUnit.net 00:00:02.01]     Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.InsertOptionalDataVisitor_PersistsVersionControlInformation [FAIL]
  Failed Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.InsertOptionalDataVisitor_PersistsVersionControlInformation [191 ms]
  Error Message:
   Expected object to be file:///C:/dev/SarifInternal/submodules/sarif-sdk/, but found file:///C:/dev/SarifInternal/.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.ConstructTestOutputFromInputResource(String inputResourceName, Object parameter) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 123
   at Microsoft.CodeAnalysis.Sarif.FileDiffingUnitTests.RunTest(String inputResourceName, String expectedOutputResourceName, Object parameter) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.Utilities.Sarif\FileDiffingUnitTests.cs:line 101
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.RunTest(String inputResourceName, OptionallyEmittedData optionallyEmittedData) in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 159
   at Microsoft.CodeAnalysis.Sarif.Visitors.InsertOptionalDataVisitorTests.InsertOptionalDataVisitor_PersistsVersionControlInformation() in C:\dev\SarifInternal\submodules\sarif-sdk\src\Test.UnitTests.Sarif\Visitors\InsertOptionalDataVisitorTests.cs:line 214

Failed!  - Failed:     2, Passed:   573, Skipped:     3, Total:   578, Duration: 6 s - Test.UnitTests.Sarif.dll (netcoreapp3.1)
```

@michaelcfanning @eddynaka

**Comment by michaelcfanning** [comment]
I'd noticed these and have fixes for them. One root cause is that the version control provenance injection mechanism is simply broken for submodules. It turns out that submodules do not have a .git directory, as our code assumes. We likely mock this behavior. In practice, however, that code fails.

**Comment by eddynaka** [comment]
@michaelcfanning , thank you for letting me know. I was already checking the pipeline if it was download the data correctly!

**Comment by eddynaka** [comment]
@lgolding , with the pr #2163 , I think that will solve this problem. Can you try and let us know, please?

**Comment by lgolding** [comment]
@eddynaka @michaelcfanning 

Yes, it solves the problem and you can close this bug. The latest `main` introduced another bug #2165, which I have a one-line fix for. PR to follow.
