### ISSUE TITLE
InvalidOperationException in MultithreadedAnalyzeCommandBase.LogCachingLogger() due to concurrent modification of enumerable

### ISSUE THREAD

**Issue by ankitr42** [microsoft/sarif-sdk#2474]
https://github.com/microsoft/sarif-sdk/blob/ed38f391b85e9a26b5e6079ad29fdd9f2b342e5e/src/Sarif.Driver/Sdk/MultithreadedAnalyzeCommandBase.cs#L310

We're seeing a System.InvalidOperationException in the above method with the following stack trace:

```
BINSKIM : error ERR999.UnhandledEngineException : System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.LogCachingLogger(TContext rootContext, IAnalysisLogger logger, TContext context, Boolean clone) in /_/src/Sarif.Driver/Sdk/MultithreadedAnalyzeCommandBase.cs:line 310
     at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.WriteResultsAsync(TContext rootContext) in /_/src/Sarif.Driver/Sdk/MultithreadedAnalyzeCommandBase.cs:line 271
  InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.LogCachingLogger(TContext rootContext, IAnalysisLogger logger, TContext context, Boolean clone)
     at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2.WriteResultsAsync(TContext rootContext)
```

Going by the class name, I believe the code in MultithreadedAnalyzeCommandBase.LogCachingError() is not thread-safe. We're seeing this issue inconsistently in some of our builds.

**Comment by eddynaka** [comment]
@marmegh Can you review this?
The stack trace above is happening for BinSkim
