### ISSUE TITLE
Multitool  convert documentation typo

### ISSUE THREAD

**Issue by Jiri-Stary** [microsoft/sarif-sdk#2730]
sarif convert

Hi i think there is a typo in the docs
https://github.com/microsoft/sarif-sdk/blob/main/docs/multitool-usage.md

: Convert a Fortify file to SARIF
Sarif.Multitool convert Current.fpr -tool FortifyFpr -output Current.sarif

running this command fails since it parses like -t ool and -o utput

Spent some time scratching my head what was wrong

**Comment by boris-ning-usds** [comment]
Oooh, I just bit this same problem. Was scratching my head all the same.

```
Run npx @microsoft/sarif-multitool convert results.fpr -tool FortifyFpr -output results.sarif
System.ArgumentException: Unrecognized tool specified: ool (Parameter 'toolFormat')
   at Microsoft.CodeAnalysis.Sarif.Converters.ToolFormatConverter.ConvertToStandardFormat(String toolFormat, Stream inputStream, IResultLogWriter outputStream, OptionallyEmittedData dataToInsert, String pluginAssemblyPath)
   at Microsoft.CodeAnalysis.Sarif.Converters.ToolFormatConverter.ConvertToStandardFormat(String toolFormat, String inputFileName, String outputFileName, FilePersistenceOptions logFilePersistenceOptions, OptionallyEmittedData dataToInsert, String pluginAssemblyPath)
   at Microsoft.CodeAnalysis.Sarif.Multitool.ConvertCommand.Run(ConvertOptions convertOptions, IFileSystem fileSystem)
```
