### ISSUE TITLE
System.FormatException error while converting Semmle CSV to SARIF

### ISSUE THREAD

**Issue by suschapp** [Microsoft/sarif-sdk#586]
Following error occurs using the Sarif conversion app.
```
System.FormatException: Input string was not in a correct format.
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
at System.Int32.Parse(String s)
at Microsoft.CodeAnalysis.Sarif.Converters.SemmleConverter.NormalizeRawMessage(String rawMessage, 
at Microsoft.CodeAnalysis.Sarif.Converters.SemmleConverter.ParseResult()
at Microsoft.CodeAnalysis.Sarif.Converters.SemmleConverter.GetResultsFromStream(Stream input)
at Microsoft.CodeAnalysis.Sarif.Converters.SemmleConverter.Convert(Stream input, IResultLogWriter output)
at Microsoft.CodeAnalysis.Sarif.Converters.ToolFormatConverter.ConvertToStandardFormat(ToolFormat toolFormat, Stream inputStream, IResultLogWriter outputStream)
at Microsoft.CodeAnalysis.Sarif.Converters.ToolFormatConverter.ConvertToStandardFormat(ToolFormat toolFormat, String inputFileName, String outputFileName, ToolFormatConversionOptions conversionOptions)
at Microsoft.CodeAnalysis.Sarif.ConvertToSarif.Program.RunConvertFile(ConvertOptions `convertOptions)`
```

Based  on my investigation, the crash is occurring in the code where its trying to parse the related location.

That code is assuming the format is in a format similar to: 
`"hbm"|"relative://some/path/myfile.cxx:176:4882:3"`

However in the file which causes an error, its not a relative file path but an actual file path. 
`"IComparable""|""file://C:/some/path/blahlib.dll:0:0:0:0"`

The file path has "C:" which introduces another colon; colons are being used to split the tokens. Thus the split occurs incorrectly and then the parsing is performed on the wrong token. If the colon is removed from C:, the crash no longer occurs.

For a csv which produces this error please contact @suschapp. I also have coded up a suggested fix as well if interested.

**Comment by lgolding** [comment]
Fixed in PR #591.
