### ISSUE TITLE
Path rebase fails if path mentioned in SARIF file differs from resolved path only in drive letter

### ISSUE THREAD

**Issue by lgolding** [Microsoft/sarif-sdk#623]
When you double-click on a result in a file that doesn't exist on your disk at the specified location, the viewer prompts with an Open File dialog. When you select the file in the correct location, the viewer should open it. But it doesn't.

Repro steps:

1. Unzip this archive to location C:\ (the root of the C: drive), which will create folder C:\EmbeddedContentDemo.

[EmbeddedContentDemo.zip](https://github.com/Microsoft/sarif-sdk/files/1322347/EmbeddedContentDemo.zip)

2. Open VS 2017 with the latest VSIX viewer installed.

3. Select menu item **Tools**, **Open Static Analysis Log File**, **Open SARIF file**. The "Open Static Analysis Results Interchange Format (SARIF) file" dialog opens.

4. Select file C:\EmbeddedContentDemo\2-IncorrectPaths.sarif, and then click **Open**. A single result appears in the Error List window.

5. Double-click the result. The "Locate missing file" dialog opens.

6. Select file C:\EmbeddedContentDemo\src\FileWithResult.cpp, and then click **Open**.

Expected: The viewer should open the selected file and highlight the line with the result.

Actual: An exception occurs:

![exception](https://user-images.githubusercontent.com/11762653/30712790-0ebf2004-9ec2-11e7-819d-09a926ad21d9.png)

Here is the ActivityLog file mentioned in the exception (renamed to .xml.txt because you can't attach an XML file to an issue):

[ActivityLog.xml.txt](https://github.com/Microsoft/sarif-sdk/files/1322375/ActivityLog.xml.txt)

The relevant part is at the end:
```
  <entry>
    <record>650</record>
    <time>2017/09/21 18:41:51.379</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Sarif.Viewer.CodeAnalysisResultManager.GetRebaselinedFileName(String uriBaseId, String fileName) in E:\src\sarif-sdk\src\Sarif.Viewer.VisualStudio\CodeAnalysisResultManager.cs:line 443
   at Microsoft.Sarif.Viewer.CodeAnalysisResultManager.TryRebaselineCurrentSarifError(String uriBaseId, String originalFilename) in E:\src\sarif-sdk\src\Sarif.Viewer.VisualStudio\CodeAnalysisResultManager.cs:line 266
   at Microsoft.Sarif.Viewer.ResultTextMarker.NavigateTo(Boolean usePreviewPane) in E:\src\sarif-sdk\src\Sarif.Viewer.VisualStudio\ResultTextMarker.cs:line 71
   at Microsoft.Sarif.Viewer.ErrorList.SarifTableControlEventProcessorProvider.EventProcessor.PreprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e) in E:\src\sarif-sdk\src\Sarif.Viewer.VisualStudio\ErrorList\SarifTableControlEventProcessorProvider.cs:line 94
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass40_0.&lt;OnEntryElementNavigate&gt;b__2(ITableControlEventProcessor p, ITableEntryHandle entry) 
  at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass60_1`1.&lt;EventProcessorHandler&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

```

**Comment by vinaykapadia** [comment]
I think I touched the Rebase code last, I’ll look into this issue.

 

-Vinay

**Comment by lgolding** [comment]
@michaelcfanning @vinaykapadia The error occurs if the path mentioned in the SARIF file, and the path you select in the Open File dialog, differ only by drive letter (for example, the SARIF file mentioned `D:\EmbeddedContentDemo\src\FileWithResults.cpp`, and you open the file `C:\EmbeddedContentDemo\src\FileWithResults.cpp`, and I understand why it happens.

The offending method, `CodeAnalysisResultManager.GetRebaselinedFileName`, contains path-parsing logic that needs to be unit tested, but it's not unit testable, because it mixes the parsing logic with calls to display the Open File dialog and to set the keyboard focus. I'm going to need to refactor it to get tests is place before I fix this.
