### ISSUE TITLE
Viewer: InvalidOperationException when opening corrupt non-SARIF log

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-sdk#721]
The Viewer should fail gracefully when it encounters invalid input.

Example: corrupt PREfast log
[C6001Example2.cpp.xml.txt](https://github.com/Microsoft/sarif-sdk/files/1568982/C6001Example2.cpp.xml.txt)

System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (54, 5).
  Source=System.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Microsoft.CodeAnalysis.Sarif.Converters.PREfastConverter.Convert(Stream input, IResultLogWriter output, LoggingOptions loggingOptions) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk-master\src\Sarif.Converters\PREFastConverter.cs:line 45
   at Microsoft.CodeAnalysis.Sarif.Converters.ToolFormatConverter.ConvertToStandardFormat(String toolFormat, Stream inputStream, IResultLogWriter outputStream, LoggingOptions loggingOptions, String pluginAssemblyPath) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk-master\src\Sarif.Converters\ToolFormatConverter.cs:line 99
   at Microsoft.Sarif.Viewer.ErrorList.ErrorListService.ProcessLogFile(String filePath, Solution solution, String toolFormat) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk-master\src\Sarif.Viewer.VisualStudio\ErrorList\ErrorListService.cs:line 55
   at Microsoft.Sarif.Viewer.OpenLogFileCommands.MenuItemCallback(Object sender, EventArgs e) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk-master\src\Sarif.Viewer.VisualStudio\OpenLogFileCommands.cs:line 260
   at Microsoft.VisualStudio.Shell.OleMenuCommand.Invoke(Object inArg, IntPtr outArg, OLECMDEXECOPT options)
   at Microsoft.VisualStudio.Shell.OleMenuCommandService.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& commandGroup, UInt32 nCmdId, UInt32 nCmdExcept, IntPtr pIn, IntPtr vOut)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& guidGroup, UInt32 nCmdId, UInt32 nCmdExcept, IntPtr pIn, IntPtr vOut)

Inner Exception 1:
XmlException: An XML comment cannot contain '--', and '-' cannot be the last character. Line 54, position 5.

**Comment by michaelcfanning** [comment]
Resolved by @EasyRhinoMSFT
