### ISSUE TITLE
Viewer: applying second fix sometimes results in exception

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [Microsoft/sarif-sdk#777]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Sarif.Viewer
  StackTrace:
   at Microsoft.Sarif.Viewer.ResultTextMarker.UpdateAtCaretPosition(CaretPosition caretPoisition) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk\src\Sarif.Viewer.VisualStudio\ResultTextMarker.cs:line 514
   at Microsoft.Sarif.Viewer.ResultTextMarker.ViewLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e) in C:\Users\v-chrmey\Documents\GitHub\sarif-sdk\src\Sarif.Viewer.VisualStudio\ResultTextMarker.cs:line 501
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

REPRO
1. Rename attached txt files to sarif/html and open .sarif in VS
2. Double-click first error list item and switch to Fixes tab
3. Apply first fix
4. SINGLE-click second error list item
5. Apply second fix
Crash.

It looks like we're trying to use the tracking span, which is only created if the user double-clicks the error list item. It seems like this should happen whenever the error list selection changes.
[AttributeFixes.sarif.txt](https://github.com/Microsoft/sarif-sdk/files/1708140/AttributeFixes.sarif.txt)

[AttributeFixes.html.txt](https://github.com/Microsoft/sarif-sdk/files/1708144/AttributeFixes.html.txt)

**Comment by EasyRhinoMSFT** [comment]
Fixed by PR #779
